services:
  web:
    build: .
    # وصل کردن پوشه فعلی به کانتینر برای اعمال تغییرات لحظه‌ای
    volumes:
      - .:/app
    # باز کردن پورت 8000 سیستم برای دسترسی به سایت
    ports:
      - "8000:8000"
    # متصل کردن ورودی ترمینال برای تعامل با کانتینر
    stdin_open: true
    tty: true